name: 🤖 Update repo cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * FRI'  # At 12:00 PM UTC, only on Friday

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update files
      run: python update.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: github-actions[bot]@users.noreply.github.com
        message: "Update cron variables"
        add: '.'
